### ISSUE TITLE
When realm closes and the bot is waiting to get into the realm, it won't search for another one

### ISSUE THREAD

**Issue by AzukiMPGH** [thomas-crane/famebot#10]
/title

**Comment by thomas-crane** [comment]
I _thought_ this was fixed when I added
```
if(!portals.Exists(ptl => ptl.ObjectId == portalId))
{
        MoveToRealms(client);
        return;
}
```
To the attempt connection method, but I also had this problem last night. Any ideas?

**Comment by moistmaster** [comment]
hmm could you make it disconnect you so it walks back up on an interval

**Comment by AzukiMPGH** [comment]
I'll be looking into fixing this if a fix hasn't been found yet, now that I have got a week off.

**Comment by thomas-crane** [comment]
Thanks @AzukiMPGH. There is still no fix but I think the problem might be that when a portal disappears it doesn't actually get removed from the `portals` list and so the code in my earlier comment actually never runs.

**Comment by AzukiMPGH** [comment]
I guess a cheap fix for this then would be to clear the portals array at the start of the OnTick method

**Comment by thomas-crane** [comment]
Fixed. See commit ef2b79c54a48cc10494e113b28d8c90ecf7e3636 for details.
`MoveToRealms(...)` only works if `gotoRealm` is true, but after `MoveToRealms(...)` exits `gotoRealm` is set to false.
Setting `gotoRealm` to true before calling `MoveToRealms(...)` from `AttemptConnection(...)` fixed this.
