### ISSUE TITLE
Inability to send messages

### ISSUE THREAD

**Issue by michael-elbert** [thomas-crane/famebot#11]
My idea for a solution: Add a textarea in the famebot window that lets you send messages. Just a suggestion.

**Comment by AzukiMPGH** [comment]
This can also be achieved by using the KRelay move library to move the character, which makes the need to send keyboard inputs unnecessary.

**Comment by thomas-crane** [comment]
From memory I think the KRelay move lib uses GOTO packets which can be problematic when there are lots of obstacles (godlands rocks) or black tiles. The text area in the GUI was always an idea in the back of my mind and it should only take 30 mins or less to implement. I will start on this soon.

**Comment by thomas-crane** [comment]
I added a chat bot GUI where you can send and receive messages.
See commit 2eeaa20a04f4f3a503a24ca3e7216671f98f2620 for more info.
