### ISSUE TITLE
When two realms are full, bot will not always go to the realm with the train on EUN2

### ISSUE THREAD

**Issue by AzukiMPGH** [thomas-crane/famebot#13]
This can be fixed by checking the amount of players in the portals' radius of 5f.
If the portal has more players around it than others, it's the fame train portal

**Comment by thomas-crane** [comment]
This is a really elegant solution, thanks for this. I will start implementing it on Wednesday when I have internet on my main computer again.

**Comment by thomas-crane** [comment]
Fixed. See 00ed2d0aa34f526baf6c49d379bdbb48f7020324 for details.
