### ISSUE TITLE
Reconnect to realm would reconnect to any realm, despite it not being the optimal one

### ISSUE THREAD

**Issue by AzukiMPGH** [thomas-crane/famebot#15]
In commit ebe44816666f5ec28a8c2850ecffccda81c763bd the added realm reconnect would ignore the optimal realm and reconnect to the realm it was in before either way. 

I'm assuming this originates from `if (client.State.LastRealm?.Name.Contains(bestName) ?? false)`
and would work better if changed to `if (client.State.LastRealm?.Name ==  "NexusPortal." + bestName)`
although I haven't tested this fix yet, this should work fine.

Edit: also as seen here: https://azuki.s-ul.eu/s5CCXcsZ I would also set the variable `bestName` in the `else` from the first if-statement

**Comment by thomas-crane** [comment]
Hopefully fixed. See commit ceba5607ae2289fc6bf97d01aabb684ca48edf8b for details.
