### ISSUE TITLE
[Typo] README.md

### ISSUE THREAD

**Issue by AzukiMPGH** [thomas-crane/famebot#16]
![vivaldi_2017-04-22_19-40-18](https://cloud.githubusercontent.com/assets/10087856/25306743/b6c3290e-2793-11e7-98bd-eaad22dbd7f2.png)

**Comment by ZackTaylor** [comment]
I'll take care of this @AzukiMPGH.

**Comment by thomas-crane** [comment]
Thanks, @ZackTaylor. PR has been merged so the issue is fixed.
