### ISSUE TITLE
Stuck near DQ or weird moving stuck at nex area 

### ISSUE THREAD

**Issue by TransfixedMPGH** [thomas-crane/famebot#18]
Jerking movements left and right seen resulting in either character stationary at the area after nexus-ing or somehow getting stuck at the right corner of daily quest (DQ) portal)

https://i.gyazo.com/f6593b801ddb7618b93ef1db3b8b7535.png

Happens every 1 in 5-10 times esp. when i leave the famebot running for more than 2 hours at a time.

**Comment by thomas-crane** [comment]
I think this is a result of the nexus only sending `NEWTICK` packets every 200ms, so if you have a character with a lot of speed you can end up going back and forth. The best solution is probably to lower the speed of the character while they are in the nexus.

**Comment by AzukiMPGH** [comment]
I'll fix this in a bit

**Comment by thomas-crane** [comment]
Thanks @AzukiMPGH for this fix. The pull request has been merged so I'll close this.
