### ISSUE TITLE
Conventionnal changes

### ISSUE THREAD

**Issue by iObsidian** [thomas-crane/famebot#2]
I just wanted to recommend changing the plugin name to something more conventional like FameBot and change the command from /bind to /fb or /famebot
Feel free to close this since it isnt really an issue
And also good job, I really like it :)

**Comment by thomas-crane** [comment]
Closing this for now but will probably reconsider this issue and create a naming convention on the Wiki at some point. 'Plugin' is quite a generic name so should probably be changed. I kind of like '/bind' because it's very descriptive of what it actually does.
