### ISSUE TITLE
Not sure if its just my problem . Error message obtained

### ISSUE THREAD

**Issue by TransfixedMPGH** [thomas-crane/famebot#22]
[Error]          An exception was thrown
within ServerPacket 
at Dictionary`2.get_Item

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Lib_K_Relay.GameData.GameDataMap`2.ByID(IDType id)
   at FameBot.Core.Plugin.OnUpdate(Client client, Packet p)
   at Lib_K_Relay.Proxy.<>c__DisplayClass37_0.<FireServerPacket>b__0()
   at Lib_K_Relay.Utilities.PluginUtils.ProtectedInvoke(Action action, String errorProvider, Type filteredException)

might be cause of the new patch not too sure of the reason.

**Comment by thomas-crane** [comment]
Any other info you have such as
+ How often this occurs
+ Where the client is when this occurs (e.g. in nexus, in a realm, on the menu screen, etc.)
+ Does this occur after a particular event (e.g. just as you enter a realm, when the bot finds a cluster, etc.)

Would be very helpful for fixing this.
I think the only place time `GameDataMap` is used is to look for rocks on the map. If the IDs were changed in the latest patch it might be causing this issue.

**Comment by thomas-crane** [comment]
Fixed. See commit b42edac377f848ac59f67d46db23ff39d42f7e70
For some reason, detecting rocks by using the GameDataMap was not working. Fixed by using the ID of the Rock Grey object for detection.
