### ISSUE TITLE
insta kick whenever i tp aft entering a realm

### ISSUE THREAD

**Issue by TransfixedMPGH** [thomas-crane/famebot#23]
doesnt give error msg. didnt have this problem before downloading this.

**Comment by TransfixedMPGH** [comment]
ps there is an error msg server protocol error
http://prntscr.com/fmfj3j

**Comment by TransfixedMPGH** [comment]
think i found the problem. problem seems to lie in the lib krelay file provided. replacing it with the one from http://www.mpgh.net/forum/showthread.php?t=1271771 seems to solve the problem

**Comment by thomas-crane** [comment]
Thanks for finding the fix. I wont be able to make the fix until later today, but feel free to make a pull request with the updated lib.

**Comment by thomas-crane** [comment]
I'm closing this for now because:
+ I can't reproduce this, and it hasn't been reported elsewhere.
+ The lib file in the `Release/` folder doesn't affect the bot.

Feel free to open it again if you keep having this issue.
