### ISSUE TITLE
Keystrokes arent being sent to client even though famebot says keys are being pressed

### ISSUE THREAD

**Issue by EmC14** [thomas-crane/famebot#27]
Even though famebot is connected, and there is no problem teleporting, my character doesn't move. The famebot shows which keys are simulated to be pressed, but the character doesn't move when any key is highlighted

**Comment by AlanBaumgartner** [comment]
Did you /bind your client?

**Comment by thomas-crane** [comment]
Not using /bind is the most likely problem. Just use the command once when you open the bot then press Stop/Start to get the bot going again.

**Comment by EmC14** [comment]
ok got it, thanks!
