### ISSUE TITLE
[Request] Checkbox to toggle Enemy Avoidance

### ISSUE THREAD

**Issue by AzukiMPGH** [thomas-crane/famebot#28]
Add a Checkbox to toggle the state of Enemy Avoidance and also add more nup's to customize it more.

**Comment by thomas-crane** [comment]
This is a good idea. I will probably add some other settings (like flash player process name) when I do this. I should be able to get started on it this weekend.

**Comment by AzukiMPGH** [comment]
Awesome stuff! I could also do it but I'm currently working on bigger stuff (having to do with blizzard, and anticheat uwu)

**Comment by thomas-crane** [comment]
This has now been implemented.

The functionality for this was added in commit 99124bb659e07999e8adc04904e0408176714350
And a checkbox was added to the GUI in commit 18e15e1562d88c6202a5b0a98f5128d654b11f87
