### ISSUE TITLE
[Request] Make auto-aim a requirement for all bots

### ISSUE THREAD

**Issue by IpilotAnEVA** [thomas-crane/famebot#33]
Having all the bots use auto-aim would greatly speed up the train. Right now barely any person in the train kill the gods.

**Comment by thomas-crane** [comment]
As much as it would benefit the train, I don't really want to enforce that people who want to use the bot also use auto aim for a few reasons:
 + Auto aim would make the bot even more obvious than it already is.
 + A lot of people who are using the bot to farm fame are probably also going for the accurate and sniper bonuses, and auto aim would most likely reduce the accuracy.
 + There are a lot of great auto aim hacks out there already, I don't particularly want to implement a custom one in the bot which is always on. What if people are already using a better one anyway?
 + You can circumvent this requirement by just not having a weapon equipped.

I would definitely encourage that people use auto aim to help the train out, but it's not something I'm going to force people to use.
