### ISSUE TITLE
Locations need an updating.

### ISSUE THREAD

**Issue by snarticuno** [thomas-crane/famebot#37]
Bot won't move to portal area, have to do it manually. Fame botting works fine.

**Comment by thomas-crane** [comment]
Please refer to this section of the readme for info on how to update the locations

> As of version `1.0.63` there is now the ability to change the fountains/realm positions which the bot will go to. This feature can be used anytime the nexus changes to avoid needing to download a new version of the bot.
You can read about these new commands, and all other commands for the bot on [this Wiki page.](https://github.com/thomas-crane/famebot/wiki/Usage-guide#bot-commands)
