### ISSUE TITLE
Bot positioning needs updating

### ISSUE THREAD

**Issue by Beetle34864** [thomas-crane/famebot#39]
I have set the camera angle to 0 and it still happens. Can you help?

**Comment by thomas-crane** [comment]
You can use the following commands to fix the positions. You should use the `fountainposition` command in a spot where you are healed by the foutains, and the `realmposition` command in a spot where you can see all of the realm portals.

 + `/famebot set realmposition` This changes the position the bot will go to when it is trying to go towards the realms. This should be used any time the Nexus is changed and the bot no longer goes to the right place.
 + `/famebot set fountainposition` This changes the position the bot will go to when it is trying to go to the fountains to heal. This should be used any time the Nexus is changed and the bot no longer goes to the right place.

**Comment by Beetle34864** [comment]
Thanks very much and a very quick  response!
