### ISSUE TITLE
Question about Realm bots in general

### ISSUE THREAD

**Issue by boftsoy** [thomas-crane/famebot#41]
From your experience, would it be possible for a Realm bot to sense/keep track of projectile locations? Thanks.

**Comment by AzukiMPGH** [comment]
Yes

**Comment by boftsoy** [comment]
Could you direct me to a code snippet that does this? 

If so, do you know if anyone has tried implementing real-time projectile avoidance?

**Comment by thomas-crane** [comment]
Projectiles are sent in `EnemyShootPacket`s and have properties such as starting location and angle. That should be most of the things you need to keep track of projectile locations.
