### ISSUE TITLE
Nexus positions need updating

### ISSUE THREAD

**Issue by AdamJamil** [thomas-crane/famebot#42]
Runs straight to the left

**Comment by thomas-crane** [comment]
Please refer to this section of the wiki:

 + `/famebot set realmposition` This changes the position the bot will go to when it is trying to go towards the realms. This should be used any time the Nexus is changed and the bot no longer goes to the right place.
 + `/famebot set fountainposition` This changes the position the bot will go to when it is trying to go to the fountains to heal. This should be used any time the Nexus is changed and the bot no longer goes to the right place.
