### ISSUE TITLE
Nexus positions need updating

### ISSUE THREAD

**Issue by MithralSky** [thomas-crane/famebot#47]
once i start the bot it runs on top left if just started instead of going north to the portals, if i move near the portals then hit start it goes in correctly and if i go in then get ported back to nexus it then move stright to the left not top left but only left

**Comment by thomas-crane** [comment]
Please refer to this section of the wiki:

 + `/famebot set realmposition` This changes the position the bot will go to when it is trying to go towards the realms. This should be used any time the Nexus is changed and the bot no longer goes to the right place.
 + `/famebot set fountainposition` This changes the position the bot will go to when it is trying to go to the fountains to heal. This should be used any time the Nexus is changed and the bot no longer goes to the right place.
