### ISSUE TITLE
Nexus positions need updating

### ISSUE THREAD

**Issue by ghost** [thomas-crane/famebot#48]
the bot walks to the top right hand side of the nexus and my camera position is set to zero

**Comment by thomas-crane** [comment]
Hi, please refer to this section of the wiki:

+ `/famebot set realmposition` This changes the position the bot will go to when it is trying to go towards the realms. This should be used any time the Nexus is changed and the bot no longer goes to the right place.
+ `/famebot set fountainposition` This changes the position the bot will go to when it is trying to go to the fountains to heal. This should be used any time the Nexus is changed and the bot no longer goes to the right place.

These commands can be used to change the Nexus positions. The first one should be used in a spot where you can see all of the realms, and the second one should be used in a spot where you are healed by the fountains. You can also use `/famebot set rp` and `/famebot set fp` to achieve the same thing.
