### ISSUE TITLE
[REQUEST] If nexus, reconnect like clients using reconnect

### ISSUE THREAD

**Issue by AlanBaumgartner** [thomas-crane/famebot#6]
When you hit 'p' it reconnects back to realm for crazyclient. My suggestion would be to have it if you nexus from anywhere besides oryx castle, it automatically reconnects you like the client using its reconnect feature.

It would bypass waiting for the realm to have an open spot again 💃

**Comment by thomas-crane** [comment]
I will look at implementing this today. As CrazyJani suggested, the best solution is to walk to the realms to check if a different realm has more players, and then to reconnect to the old realm if this is not the case.

**Comment by AzukiMPGH** [comment]
@thomas-crane @AlanBaumgartner I think you guys might enjoy this a little ヽ(・∀・)ﾉ
https://youtu.be/f4ZDt9YcgwU

**Comment by AlanBaumgartner** [comment]
@AzukiMPGH And thats pretty sick. Forever wishing I could apply python knowledge to realm :^(

**Comment by thomas-crane** [comment]
@AzukiMPGH Video was removed by user :(
Also, I saw in the video you posted to MPGH you managed to get reconnecting working. It would be awesome if you could share your method or make a pull request when it's done!

**Comment by thomas-crane** [comment]
Added this in commit ebe44816666f5ec28a8c2850ecffccda81c763bd
