### ISSUE TITLE
Reconnect doesn't work  

### ISSUE THREAD

**Issue by ryanrota** [thomas-crane/famebot#9]
When i get nexuses instead of my character moving up nexus and going to the realm, my character moves in a diagonal direction to the left and gets stuck on a wall.  
Is this just me?

**Comment by AzukiMPGH** [comment]
This is due to DECA changing Nexus Positions. This can be fixed easily with a small variable change, no biggie c:

**Comment by ryanrota** [comment]
Ok thanks for that! How do you get the updated variables or are they not out yet?

**Comment by AzukiMPGH** [comment]
Currently on the original repo (this one) the updated variables are not up yet. I have a fork though where they're already up.

**Comment by ryanrota** [comment]
Thanks for that AzukiMPGH. I am just going to wait for the download file to come up as i am unsure about the script stuff :). Thanks for your time and work!

**Comment by ryanrota** [comment]
I take it that the download with the updated files will be posted here?

**Comment by thomas-crane** [comment]
Yeah, next update should be out today
